site_name: Eressea
site_url: https://zendev1710.github.io/eressea-doc
repo_url: https://github.com/zendev1710/eressea-doc
site_description: "Eressea documentation."
site_author: zendev1710

theme:
  name: material
  # favicon: assets/images/favicon.ico
  # font: false
  # https://materialdesignicons.com/
  # icon:
  #   logo: material/human-greeting
  #   logo_tech: material/bash
  #   logo_fpv: material/quadcopter
  # features:
  #   - navigation.tabs
  #   - navigation.expand
  #   - navigation.sections
  #   - toc.integrate
  # custom_dir: theme_overrides
# language: en

# extra_css:
#   - assets/stylesheets/extra.css
copyright: Copyright &copy; 2025-2026 zendev1710.

plugins:
  # - categories
  - awesome-nav:
      filename: .pages
  - redirects
  - search
  # - autorefs
  # - live-edit
  - i18n:
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: fr
          name: Français
          build: true
        - locale: de
          name: Deutsch
          build: true
      docs_structure: suffix
      # build_only_locale: !ENV [BUILD_ONLY_LOCALE]

# https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/?h=language
extra:
  alternate:
    - name: English
      link: /eressea-doc/ 
      lang: en
    - name: Français
      link: /eressea-doc/fr/ 
      lang: fr
    - name: Deutsch
      link: /eressea-doc/de/
      lang: de

markdown_extensions:
  - admonition
  # - attr_list
  - pymdownx.details
  - pymdownx.superfences
  