site_name: Eressea
site_url: https://zendev1710.github.io/eressea-doc
repo_url: https://github.com/zendev1710/eressea-doc
site_description: "Eressea documentation."
site_author: zendev1710

theme:
  font:
    # text: Roboto
    # TODO: try some fonts like : Merriweather, Lora, Playfair Display (PT Serif? Crimson Text?)
    text: Roboto
    code: Fira Code
    ##text: Merriweather
    ##code: Roboto Mono
  features:
    - header.autohide
    - content.code.copy
    # what is it ?
    - content.tabs.link
    - content.tooltips
    - navigation.indexes
    # not compatible with i18n
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    - navigation.sections
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - tables
    - toc.follow

    # - navigation.expand
    # - toc.integrate

  palette:
        # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: indigo
      #primary: indigo
      #accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      # test colors
      primary: blue grey
      accent: amber
      #primary: indigo
      #accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

  name: material
  logo: assets/images/logo.png
  favicon: assets/images/favicon.ico
  # font: false
  # https://materialdesignicons.com/
  # icon:
  #   logo: material/human-greeting
  #   logo_tech: material/bash
  #   logo_fpv: material/quadcopter
  # features:
  #   - navigation.tabs
  #   - navigation.expand
  #   - navigation.sections
  #   - toc.integrate
  # custom_dir: theme_overrides
# language: en

extra_css:
  - assets/css/extra.css
  - assets/css/fantasy.css
  - https://unpkg.com/katex@0/dist/katex.min.css

extra_javascript:
  - javascripts/katex-init.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
  # our own scripts
  - javascripts/formulas-try.js

copyright: Copyright &copy; 2025 Cyril Guillon

plugins:
  # - categories
  - alias
      # use_anchor_titles: true
      # use_page_icon: true
  # - awesome-nav
  - redirects
  - search
  # - autorefs
  # - live-edit
  - i18n:
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: fr
          name: Français
          build: true
          nav_translations:
            Home: Accueil
            Getting-started: Premiers pas
            Rules: Règles
            Introduction: Introduction
            Gameplay: Jeu
            Exploration: Exploration
            War: Guerre
            Magic: Magie
            Alchemy: Alchimie
            Orders: Ordres
            Misc: Divers
            References: Références
            Help: Aide
            Weekly reports: Rapport hebdomadaire
            Hints: Remarques
            Beginner tips: Conseils pour débutants
            Basics: Bases
            Sending orders: Envoi des ordres
            Sending orders from Magellan: Envoi des ordres depuis Magellan
            Puppy protection: Protection du chiot
            The World: Le Monde d'Eressea
            Factions and units: Factions et unités
        - locale: de
          name: Deutsch
          build: true
          nav_translations:
            Home: Hauptseite
            Getting-started: Erste Schritte
            Gameplay: Spielablauf
            Exploration: Erforschung
            Production: Produktion
            War: Krieg
            Magic: Magie
            Alchemy: Alchimie
            Orders: Befehle
            References: Referenzen
            Help: helfen
      docs_structure: suffix
      # build_only_locale: !ENV [BUILD_ONLY_LOCALE]

# https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/?h=language
extra:
  alternate:
    - name: English
      link: /eressea-doc/
      lang: en
    - name: Français
      link: /eressea-doc/fr/
      lang: fr
    - name: Deutsch
      link: /eressea-doc/de/
      lang: de

# Extensions
markdown_extensions:

# Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  # Python Markdown Extensions
  # pymdownx.arithmatex is for Mathjax
  # but we use katex via js
  - pymdownx.arithmatex:
      # TODO: check if generic is needed
      generic: true
      #inline_syntax: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home:
    - index.md
  - Getting-started:
    - Rules: rules.md
    - Introduction: introduction.md
    - Eressea: eressea.md
    - Weekly reports: weekly-report.md
    - Hints: hints.md
    - Beginner tips: getting-started-tips.md
    - Basics: basics.md
    - Sending orders: commands-send.md
    - Sending orders from Magellan: commands-send-from-magellan.md
    - Puppy protection: puppy-protection.md
  - Gameplay:
    - The World: world.md
    - Factions and units: factions.md
    - Races: races.md
    - skills-modifiers.md
    - skills.md
    - camouflage.md
  - Exploration:
    - travel.md
    - sailing.md
  - Production:
    - production.md
    - resources.md
    - items.md
    - roads.md
    - ships.md
    - buildings.md
    - castles.md
    - buildings-others.md
    - faction-pool.md
    - silver.md
    - items-pool.md
  - War:
    - war.md
    - alliances.md
    - tactic.md
    - armed.md
  - Magic:
    - magic.md
    - magic-schools.md
    - familiars.md
    - spells-list.md
    - spells-descriptions.md
    #- magical-herb-bag.md
  - Alchemy:
    - alchemy.md
    - herbs.md
  - Orders:
    - commands.md
    - commands-sequence.md
    - commands-list.md
    - first-round.md
    # - puppy-protection.md
    # - commands-send.md
  # - Commands:
    - cmd-attack.md
    - cmd-banner.md
    - cmd-buy.md
    - cmd-carry.md
    - cmd-cast.md
    - cmd-claim.md
    - cmd-combat.md
    - cmd-combatspell.md
    - cmd-comment.md
    - cmd-comment-slash.md
    - cmd-contact.md
    - cmd-default.md
    - cmd-describe.md
    - cmd-destroy.md
    - cmd-email.md
    - cmd-end.md
    - cmd-enter.md
    - cmd-entertain.md
    - cmd-eressea.md
    - cmd-follow.md
    - cmd-forget.md
    - cmd-give.md
    - cmd-group.md
    - cmd-grow.md
    - cmd-guard.md
    - cmd-help.md
    - cmd-hide.md
    - cmd-language.md
    - cmd-learn-auto.md
    - cmd-learn.md
    - cmd-leave.md
    - cmd-locale.md
    - cmd-make.md
    - cmd-message.md
    - cmd-move.md
    - cmd-name.md
    - cmd-next.md
    - cmd-number.md
    - cmd-option.md
    - cmd-origin.md
    - cmd-password.md
    - cmd-pay-not.md
    - cmd-piracy.md
    - cmd-plant.md
    - cmd-prefix.md
    - cmd-promote.md
    - cmd-quit.md
    - cmd-recruit.md
    - cmd-region.md
    - cmd-research.md
    - cmd-reserve.md
    - cmd-ride.md
    - cmd-route.md
    - cmd-sell.md
    - cmd-show.md
    - cmd-sort.md
    - cmd-spy.md
    - cmd-steal.md
    - cmd-tax.md
    - cmd-teach.md
    - cmd-unit.md
    - cmd-use.md
    - cmd-work.md
    # - commands-extended.md
    # - commands-list.md
    # - commands-send-from-magellan.md
    # - misc
    # - weekly-report.md
  - Misc:
    - Development:
      - development.md
      - auto-event-response.md
      - auto-learning-chains.md
      - auto-trading.md
      - auto-transport.md
      - auto-way-finding.md
      - optimize-learning-chains.md
      - optimize-production.md
      - optimize-transport.md
      - optimize-way-finding.md
      - commands-extended.md
      - reports.md
      - cr-format.md
      - move-template.md
    - Tools:
      - magellan.md
      - csmapfx.md
      - echeck.md
      - fftools.md
      - vorlage.md
      - atlantis.md
      - ehmv.md
    - Events:
      - birthday-cake.md
      - christmas.md
      - christmas-tree.md
    # TODO: begin
    - farmers-hike.md
    - farmers-proliferation.md
    - plague.md
    # - the-third-age.md
    - xontormia-express.md
    # TODO: end
  - References:
      - terrains.md
      - skills-list.md
      - war-tables.md
      - potions-and-herbs.md
      - Magic:
        - magic-school-cerddor.md
        - magic-school-draig.md
        - magic-school-gwyrrd.md
        - magic-school-illaun.md
        - magic-school-tybied.md
      - Creatures:
        - monsters.md
        - dream-eye.md
        - iron-golem.md
        - stone-golem.md
        - mountain-guard.md
        - mistletoe.md
        - snowman.md
        - toad.md
      - Items:
        - adamantium-armor.md
        - adamantium.md
        - laen.md
        - mallorn.md
        - amulet-of-true-sight.md
        - antimagic-crystal.md
        - belt-of-troll-strength.md
        - dragonblood.md
        - dragonhead.md
        - flaming-sword.md
        - magical-herb-pouch.md
        - negative-weight-bag.md
        - ring-of-invisibility.md
        - ring-of-power.md
        - shell.md
        - sphere-of-invisibility.md
        - stardust.md
        - sun-sail.md
        - pentagram-and-tirawon.md
  - Help:
    - tips-and-tricks.md
    - tutorials.md
    - faq.md
    - troubleshootings.md
    - play-too-much-if.md
    - Credits:
      - thanks.md
      - contributors.md
      - player-pages.md
      - eressea-story.md
      - the-third-age.md
