version: "3"

vars:
  # see:
  # - https://stackoverflow.com/a/61612842 for UTF8 characters with git diff
  # - https://unix.stackexchange.com/a/330662 for avoid exit code 1 with grep
  MODIFIED_FILES:
    sh: git -c core.quotepath=false --no-pager diff --no-renames --name-only --diff-filter=ACM origin/main | { grep -E "(.md$)" || true; }
  MODIFIED_FILES_INLINE:
    sh: echo "{{.MODIFIED_FILES}}" | tr '\n' ' '

tasks:
  install:
    desc: Install all necessaries dependencies (dev & mkdocs)
    cmds:
      - task: install:mkdocs
      - task: install:dev

  install:mkdocs:
    desc: Install mkdocs, theme and plugins
    cmds:
      - pip install --upgrade -r requirements.txt

  install:dev:
    desc: Install dev tools
    cmds:
      - |
        npm install -g \
          markdownlint-cli2 \
          markdown-link-check \
          cspell \
          @cspell/dict-fr-fr

  run:
    desc: Serve documentation
    env:
      ENABLE_GIT_PLUGINS: false
    cmds:
      - mkdocs serve

  build:
    desc: Build documentation
    env:
      ENABLE_PDF_PLUGIN: 1
    cmds:
      - mkdocs build

  lint:
    desc: Lint documentation
    cmds:
      - task: lint:md
      - task: lint:spell
      - task: lint:link

  # into a git bash or WSL shell
  lint:md:
    desc: Lint all the markdown files with markdownlint
    cmds:
      - markdownlint-cli2 "docs/*.md"

  lint:link:
    desc: Lint all the markdown links with markdown-link-check
    cmds:
      - markdown-link-check --quiet docs

  lint:spell:
    desc: Spell check all the markdown files with cspell
    cmds:
      - cspell lint docs -c cspell.yml

  lint:spell-fr:
    desc: Spell check all the french markdown files with cspell
    cmds:
      - cspell lint docs/*.fr.md -c cspell.yml

  lint:spell-de:
    desc: Spell check all the german markdown files with cspell
    cmds:
      - cspell lint docs/*.de.md -c cspell.yml

  lint:spell-en:
    desc: Spell check all the english markdown files with cspell
    cmds:
      - cspell lint "docs/*.md" -c cspell.yml -e *.fr.md -e *.de.md

  # into a git bash or WSL shell
  lint:md-on-changes:
    desc: Lint the modified markdown files with markdownlint (exit status code 2 if no modified files, 1 for an error, 0 otherwise)
    cmds:
      - "if [[ -n \"{{.MODIFIED_FILES}}\" ]]; then markdownlint-cli2 {{.MODIFIED_FILES_INLINE}}; else echo 'no modified markdown, lint ignored'; exit 2; fi"

  lint:spell-changes:
    desc: Spell check the modified markdown files with cspell (exit status code 2 if no modified files, 1 for an error, 0 otherwise)
    cmds:
      - "if [[ -n \"{{.MODIFIED_FILES}}\" ]]; then echo \"{{.MODIFIED_FILES}}\" | cspell lint -c cspell.yml --file-list stdin; else echo 'no modified markdown, lint ignored'; exit 2; fi"

  lint:link-changes:
    desc: Lint the modified markdown links with markdown-link-check (exit status code 2 if no modified files, 1 for an error, 0 otherwise)
    cmds:
      - "if [[ -n \"{{.MODIFIED_FILES}}\" ]]; then echo \"{{.MODIFIED_FILES}}\" | xargs -l1 markdown-link-check --quiet -c .markdown-link-check.json; else echo 'no modified markdown, lint ignored'; exit 2; fi"


  lint:link:all:
    desc: Lint all markdown links with markdown-link-check
    cmds:
      - "if [[ -n \"{{.MODIFIED_FILES}}\" ]]; then find \"docs/\" -name \"*.md\" -print0 | xargs -0 -n1 markdown-link-check --quiet -c .markdown-link-check.json; else echo 'no modified markdown, lint ignored'; exit 2; fi"

  lint:link:wget:
    desc: Lint all markdown links with wget (mkdocs server must running)
    cmds:
      - wget --recursive --spider --force-html --level=100 -nv -e robots=off -p -S http://127.0.0.1:8000

  lint:link:permalink:
    desc: Check that all pages contains a permalink definition
    cmds:
      - |
        set +e
        error=0
        for file in {{.MODIFIED_FILES_INLINE}}; do
          echo "Vérification du permalink dans le fichier : ${file}"
          grep -E '^permalink: \w+' $file > /dev/null
          if [ $? -ne 0 ]; then
            error=$((error+1))
            echo "Permalink missing in file $file"
          fi
        done
        if [ $error -gt 0 ]; then
          echo "One or more documentation files are missing a permalink"
          exit $error
        fi
