[metadata]
license = MIT
project = Eressea Documentation

[docs/**/*.de.md]
# German is the source language
file_format = markdown
base_file_name = 
language_regex = ^(?P<path>.*)\\.(?P<language>[a-z]{2})\\.md$

[docs/**/*.fr.md]
# French translation
file_format = markdown
base_file_name = 
language_regex = ^(?P<path>.*)\\.(?P<language>[a-z]{2})\\.md$
new_base = docs/**/*.de.md
language = fr

[docs/**/*.md]
# English translation (files without language suffix)
file_format = markdown
base_file_name = 
language_regex = ^(?P<path>.*)\\.md$
new_base = docs/**/*.de.md
language = en
